services:
  backend:
    build: ./backend
    # We don't map ports here because only Nginx needs to talk to Go
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

  frontend:
    build: ./frontend
    ports:
      - "80:80" # Maps port 80 on your host machine to port 80 in the container
    depends_on:
      - backend
    restart: always
  db:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: "${DB_USER:?error: DB_USER not set}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?error: DB_PASSWORD not set}"
      POSTGRES_DB: "${DB_NAME:?error: DB_NAME not set}"
    ports:
      - "${DB_PORT:?error: DB_PORT not set}:5432"
    volumes:
      # Mount the init.sql file to run automatically
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Persist database data even if the container stops
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
