# Stage 1: Build the Go binary
FROM golang:1.26-alpine AS builder
WORKDIR /app

# 1. Copy both go.mod AND go.sum because you are using pgxpool
COPY go.mod go.sum ./ 
RUN go mod download

COPY . .

# 2. Point the build command to the correct location of main.go
RUN go build -o iot-monitor-interface-api ./cmd/server/main.go

# Stage 2: Create the minimal production image
FROM alpine:3.24
WORKDIR /app
COPY --from=builder /app/iot-monitor-interface-api .
EXPOSE 8081
CMD ["./iot-monitor-interface-api"]