<template>
  <div class="flex flex-col h-full w-full p-4" :style="{ backgroundColor: widgetData.widgetColor?.bgHex || '#ffffff' }">
    
    <div v-if="config.showHeader" class="bg-white px-4 py-3 border border-slate-200 shadow-sm z-10">
      <h3 class="m-0 text-base font-extrabold text-black tracking-wide">
        {{ widgetData?.widgetLabel || 'New Text' }}
      </h3>
    </div>

    <div class="flex-1 w-full relative overflow-y-auto"
         :class="{ 'bg-white border-x border-b border-slate-200 p-4': config.showHeader, 'p-2': !config.showHeader }">
      
      <!-- ⚡ v-html renders the rich text generated by the config editor -->
      <div class="w-full break-words rich-text-container"
           v-html="config.content || 'Double-click or right-click to configure this text block...'"
           :style="{ 
             textAlign: config.textAlign, 
             fontSize: config.fontSize + 'px', 
             color: config.textColor 
           }">
      </div>
      
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';

const props = defineProps({
  widgetData: {
    type: Object,
    default: () => ({})
  }
});

const config = computed(() => {
  const customData = props.widgetData?.customChartData || {};
  return {
    content: customData.content || '',
    showHeader: customData.showHeader !== undefined ? customData.showHeader : true,
    textAlign: customData.textAlign || 'left',
    fontSize: customData.fontSize !== undefined ? customData.fontSize : 14,
    textColor: customData.textColor || '#334155' 
  };
});
</script>

<style scoped>
/* Restores default browser styling that Tailwind CSS strips away */
.rich-text-container :deep(b),
.rich-text-container :deep(strong) {
  font-weight: 700;
}

.rich-text-container :deep(i),
.rich-text-container :deep(em) {
  font-style: italic;
}

.rich-text-container :deep(u) {
  text-decoration: underline;
}

.rich-text-container :deep(ul) {
  list-style-type: disc;
  padding-left: 1.5rem;
  margin-top: 0.5rem;
  margin-bottom: 0.5rem;
}

.rich-text-container :deep(ol) {
  list-style-type: decimal;
  padding-left: 1.5rem;
  margin-top: 0.5rem;
  margin-bottom: 0.5rem;
}

.rich-text-container :deep(li) {
  margin-bottom: 0.25rem;
}
</style>